name: Deploy EC2 with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

# Added block to destroy all in one START
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
# Added block to destroy all in one END

# Code to create START
    #  - name: Terraform Plan
    #    run: terraform plan -input=false -var="key_name=key_pair_learn_2"

    #  - name: Terraform Apply
    #    run: terraform apply -auto-approve -input=false -var="key_name=key_pair_learn_2"
# Code to create END